---
- name: Install Apache Server
  hosts: ims_get3@172.19.81.174  # Replace with your inventory
  become: yes  # Allow the use of sudo without a password due to Polkit rules
  tasks:
    - name: Update the local package cache
      ansible.builtin.apt:
        update_cache: yes
 
    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
 
    - name: Start the Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes  # Ensure Apache starts on boot
 
    - name: Ensure the firewall allows HTTP and HTTPS traffic
      ansible.builtin.ufw:
        rule: allow
        name: 'Apache Full'

has context menu
