---
- name: Install and Start Apache
  hosts: ims_get3@172.19.81.174
  become: yes
  tasks:
    - name: Update the local package cache
      apt:
        update_cache: yes

    - name: Install Apache webserver
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
