---
- name: Install and start Apache server
  hosts: ims_get3@172.19.81.174
  become: yes  # This allows the tasks to run with sudo privileges
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2  # The package name for Apache
        state: present  # Ensure Apache is installed
        update_cache: yes  # Update the apt cache before installing
        cache_valid_time: 3600
 
    - name: Ensure Apache is running
      ansible.builtin.service:
        name: apache2  # The service name for Apache
        state: started  # Ensure the service is started
        enabled: yes  # Ensure the service starts on boot
