---
- name: Install and Start Apache
  hosts: ims_get3@172.19.81.174
  become: yes
  become_method: sudo
  tasks:
    - name: Update the local package cache
      ansible.builtin.apt:
        update_cache: yes
 
    - name: Install Apache webserver
      ansible.builtin.apt:
        name: apache2
        state: present
 
    - name: Start Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
