---
- name: Install Apache on Target Host
  hosts: ims_get3@172.19.81.174
  become: yes
  become_method: sudo
 
  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache considered valid for 1 hour
      register: apt_update
      retries: 5
      delay: 5
      until: apt_update is succeeded
 
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
      register: apache_install
      retries: 5
      delay: 5
      until: apache_install is succeeded
 
    - name: Ensure Apache is started and enabled
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes

has context menu
