---
- name: Install and configure Apache
  hosts: ims_get3@172.19.81.174
  become: yes
  become_method: sudo
  tasks:
    - name: Update the local package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600  # Cache is valid for 1 hour
 
    - name: Install Apache2
      ansible.builtin.apt:
        name: apache2
        state: present
 
    - name: Ensure Apache is started and enabled
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes
 
    - name: Allow HTTP traffic through the firewall
      ansible.builtin.command: ufw allow 'Apache'
      args:
        warn: false
 
    - name: Allow HTTPS traffic through the firewall
      ansible.builtin.command: ufw allow 'Apache Full'
      args:
        warn: false
 
    - name: Ensure UFW is enabled
      ansible.builtin.command: ufw enable
      args:
        warn: false
