---
- name: Install IIS on Windows
  hosts: 172.19.80.236  # Target the Windows group
  tasks:
    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present

    - name: Start IIS service
      win_service:
        name: W3Svc
        state: started  # Just use 'state' to start the service
