---
- name: Manage MySQL Service
  hosts: ims_get3@172.19.81.174
  become: yes
  tasks:
    - name: Test sudo access
      ansible.builtin.command: sudo whoami
      register: sudo_test

    - name: Output sudo test result
      debug:
        var: sudo_test
        
    - name: Attempt to restart MySQL service
      ansible.builtin.command: sudo systemctl restart mysql
      register: mysql_restart
      ignore_errors: yes

    - name: Debug MySQL restart output
      debug:
        var: mysql_restart

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Display MySQL service state
      debug:
        msg: "MySQL service is currently {{ ansible_facts.services['mysql'].state }}"

    - name: Toggle MySQL service
      ansible.builtin.service:
        name: mysql
        state: "{{ 'stopped' if ansible_facts.services['mysql'].state == 'running' else 'started' }}"
      register: service_toggle

    - name: Output result of service toggle
      debug:
        var: service_toggle




