---
- name: Manage MySQL Service
  hosts: ims_get3@172.19.81.174
  become: yes
  become_user: root
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check if MySQL service is present
      debug:
        msg: "MySQL service is present and currently {{ ansible_facts.services['mysql'].state }}"

    - name: Start MySQL service if stopped
      ansible.builtin.systemd:
        name: mysql
        state: started
      when: ansible_facts.services['mysql'].state != 'running'
