---
- name: Manage MySQL Service
  hosts: ims_get3@172.19.81.174
  become: yes
  become_method: sudo
  become_user: ims_get3
  vars:
    ansible_become_password: "qwert1"
  tasks:
    - name: Debug service status before starting
      command: systemctl status mysql
      register: mysql_status
      ignore_errors: yes

    - debug:
        var: mysql_status.stdout_lines

    - name: Start MySQL service
      ansible.builtin.systemd:
        name: mysql
        state: started
      when: ansible_facts.services['mysql'].state != 'running'
