---
- name: Manage MySQL Service
  hosts: ims_get3@172.19.81.174
  become: yes
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check if MySQL service is present
      debug:
        msg: "MySQL service is present and currently {{ ansible_facts.services['mysql'].state }}"
      when: "'mysql' in ansible_facts.services"

    - name: Start MySQL service if stopped
      ansible.builtin.service:
        name: mysql
        state: started
      when: ansible_facts.services['mysql'].state != 'running'

    - name: Output result of MySQL service status
      debug:
        msg: "MySQL service is now {{ ansible_facts.services['mysql'].state }}"
      when: "'mysql' in ansible_facts.services"
