---
- name: Manage MySQL Service
  hosts: all
  become: yes
  become_method: sudo
  become_user: ims_get3
  vars:
    ansible_become_password: pass123$
  tasks:
    - name: Gather facts
      setup:

    - name: Check MySQL service status
      command: systemctl is-active mysql
      register: mysql_service_status
      ignore_errors: yes

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started
      when: mysql_service_status.stdout != "active"
      
    - name: Ensure MySQL service is running
      systemd:
        name: mysql
        state: started
      when: mysql_service_status.stdout == "inactive"
