---
- name: Upgrade Ubuntu Packages
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure no dpkg frontend lock exists
      ansible.builtin.shell: |
        sudo rm -f /var/lib/dpkg/lock-frontend
        sudo rm -f /var/cache/apt/archives/lock

    - name: Upgrade all installed packages
      ansible.builtin.apt:
        upgrade: dist
