---
- name: Upgrade Ubuntu Packages
  hosts: all
  become: yes
  tasks:
    - name: Ensure no dpkg frontend lock exists
      ansible.builtin.command: 
        cmd: "rm -f /var/lib/dpkg/lock-frontend /var/cache/apt/archives/lock"
      ignore_errors: yes

    - name: Upgrade all installed packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      become: yes
