---
- name: Upgrade APT Packages
  hosts: ims_get3@172.19.81.174
  become: yes
  tasks:
    - name: Upgrade all installed packages
      ansible.builtin.apt:
        upgrade: dist  # Use 'full-upgrade' for Ubuntu, 'dist' is used to ensure all packages are upgraded.
        cache_valid_time: 3600
